### ISSUE TITLE
[fix]: if this plugin called with object arguments

### ISSUE THREAD

**Issue by GitScrum** [posthtml/posthtml-postcss#10]

**Comment by devinus** [comment]
It's not currently possible to use this with `posthtml-load-config`, is that right?

**Comment by GitScrum** [comment]
i`m afraid that yes

**Comment by michael-ciniawsky** [comment]
@devinus hi, stay with me i'm currently finishing **postcss**-load-config, but i need to test and make the PR's for grunt, gulp, webpack, broccoli, express/koa-middleware first. Then the same for posthtml again. few days hopefully, want to be notified? and can you explain what's not working, if it's an issue with the current load-config logic :). postcss-load-config has to work with posthtml-postcss either passing the plugins, options with posthtml-load-config or  inline and i will integrate postcss-load-config into the plugin which will load the postcss.config.js if no options are set with posthtml.
