### ISSUE TITLE
Load PostCSS config by default

### ISSUE THREAD

**Issue by silvenon** [posthtml/posthtml-postcss#31]
I suggest loading PostCCS config file by default, e.g. `postcss.config.js`, unless a configuration is specified. It makes sense that you'd want the same configuration that you're using for external CSS files.

**Comment by silvenon** [comment]
I'm trying to figure out how to add this in a way that makes sense. Initially I thought of `posthtml-postcss` using the project's PostCSS configuration if no arguments are passed. However, PostCSS adds a warning if `from` is not set, but this can only be set through the 2nd argument. 😬 My suggestion is to merge first two arguments of `posthtml-postcss`, what do you think?

**Comment by Scrum** [comment]
@silvenon Sounds good, I would see how it would look

**Comment by Scrum** [comment]
@silvenon if you use `posthtml-cli` you can see that it passes a parameter `from` which can be used

https://github.com/posthtml/posthtml-cli/blob/27c87483951e9638a321988bb2a951d05351bc80/src/cli.js#L97

**Comment by silvenon** [comment]
Yep, file name is accessible from the configuration context so I can pass it to the plugin configuration, but it would be cool if it was being passed e.g. as the 2nd argument of the plugin itself, after `tree`. But I have no idea how good of an idea that is, but it doesn't matter now, since I'll be changing the API of the plugin.

**Comment by Scrum** [comment]
> but it would be cool if it was being passed e.g. as the 2nd argument of the plugin itself, after tree

You can refer to these parameters from tree 
https://github.com/posthtml/posthtml/blob/a3b829fa5c5d3d932dcb5e11b6652976047bd13a/lib/index.js#L38-L48

**Comment by silvenon** [comment]
Great! That was the missing ingredient! 🎉
