### ISSUE TITLE
Source .html file names are not passed into stylelint reporter output

### ISSUE THREAD

**Issue by web-padawan** [posthtml/posthtml-postcss#5]
When running posthtml-postcss + stylelint, the output only contains numbers of extracted partials, but not real file names. So it is impossible to understand where the warning reason is located.

You can find a working example in my [polymer sandbox](https://github.com/web-padawan/polymer-sandbox),  just run `npm i && gulp lint:css`. 

**Current config**
```
gulp.task('lint:css', function() {
  return gulp.src('src/components/**/*.html')
    .pipe($.posthtml(
        postcss([
          stylelint(),
          reporter({
            noPlugin: true
          })
        ])
    ))
  .pipe(gulp.dest(dist()));
});
```
**Example output.**
```
<input css 1>
2:7     ‼  Expected indentation of 0 spaces (indentation) [stylelint]
3:9     ‼  Expected indentation of 2 spaces (indentation) [stylelint]
4:7     ‼  Expected indentation of 0 spaces (indentation) [stylelint]
5:4     ‼  Unexpected missing newline at end of file (no-missing-eof-newline) [stylelint]
```
Do I have to provide some special reporter config to get source file names?
@ai PTAL.

BTW, it also triggers "no-missing-eof-newline" warnings at the end of each partial, which seems not to be meaningful in this case (as `<style>` tag content doesn't have to end with newline).

**Comment by zxqfox** [comment]
What name you expect here?

**Comment by web-padawan** [comment]
I mean the name of .html file from where `<style>` tag content was parsed. E. g. `my-component.html`

**Comment by zxqfox** [comment]
So we also should shift locations somehow, right? Is it possible now?
I mean for example `2:7` is incorrect line and column numbers.

**Comment by web-padawan** [comment]
I've also noticed that line and column numbers are likely to be realtive to `<style>` tag, but not the whole file. I'm not sure that shifting is possible. It would be nice at least to display file names. BTW what if we have several `<style>` tags in the same .html file?

**Comment by zxqfox** [comment]
> I'm not sure that shifting is possible.

Why? ;-D

**Comment by web-padawan** [comment]
Well, what if we pass line number for each occurence of `<style>` tag in order to shift locations? Is it a subject for feature-request to `posthtml` itself?

**Comment by voischev** [comment]
Maybe you create PR in `posthtml-parser`?

**Comment by GitScrum** [comment]
@web-padawan @voischev try branch milestone-0.2.1

**Comment by web-padawan** [comment]
**Before:**
<input css 1>
2:7	⚠  Expected indentation of 0 spaces (indentation)
3:9	⚠  Expected indentation of 2 spaces (indentation)
4:7	⚠  Expected indentation of 0 spaces (indentation)
5:4	⚠  Unexpected missing newline at end of file (no-missing-eof-newline)

**After:**
<input css 1>
2:3	⚠  Expected indentation of 0 spaces (indentation)
3:1	⚠  Expected indentation of 2 spaces (indentation)
4:3	⚠  Expected indentation of 0 spaces (indentation)

**After (code reformatted):**
No errors.

My conclusion: code inside `<style>` tag should be formatted as follows: 
```
<style>
:host {
  dipslay: block
}
</style>
```
Thanks! Now the  only thing is to get the file name.

**Comment by GitScrum** [comment]
@web-padawan 

> My conclusion: code inside `<style>` tag should be formatted as follows:

Yep, because of last line. I fixed, you need pull up update.

**Comment by web-padawan** [comment]
Now indentation is checked as expected, thanks. The following code is OK:
```
<style>
  :host {
    dipslay: block
  }
</style>
```

**Comment by GitScrum** [comment]
@web-padawan close this issue ?

**Comment by web-padawan** [comment]
Yes, thanks. I will open a new one for passing file names in `posthtml-parser` as @voischev suggested.
